### ISSUE TITLE
starting point

### ISSUE THREAD

**Issue by ThibaultGROUEIX** [Profactor/continuous-remeshing#2]
Hi @wpalfi ,

Thanks for this very nice work. 
Can you please share in the README.md a few command lines to start playing with your codebase ? 
For instance, how would I reproduce the `5_smilodon_rib.mp4`  ?

Thanks and again, this work looks awesome!
-Thibault

**Comment by wpalfi** [comment]
Hi Thibault,
I added a link to example.py. You probably already found that.

If you want to reproduce 5_smilodon_rib.mp4: Take [paper/comparison/video.py](paper/comparison/video.py) with model='smilodon' and uncomment the lines https://github.com/Profactor/continuous-remeshing/blob/2e556421a6096701519c4f106d4af1f0588e19dd/paper/comparison/video.py#L17-L18
